---
- calls:
    - "action"
  help: What action to take
  dest: action
  env: PLUGIN_ACTION

- calls:
    - "--vault_addr"
  action: store
  dest: vault_address
  help: Address for Vault instance
  env: VAULT_ADDR

- calls:
    - "--vault_token"
  action: store
  dest: vault_token
  help: Address for Vault instance
  env: VAULT_TOKEN

- calls:
  - "--vault_ca"
  action: store
  dest: v_ca
  help: Certificate authority path for Vault
  env: VAULT_CACERT

- calls:
    - "--dry_run"
  action: store_true
  dest: dry_run
  help: Use this to print the commands that would be executed instead of actually executing them.
  env: DRY_RUN